version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rag-network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network

  # RAG Pipeline Service (for running the pipeline)
  rag-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-pipeline
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password123
      - MONGO_DATABASE=admin
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - mongodb
      - qdrant
    networks:
      - rag-network
    volumes:
      - ./models:/app/models
    command: python pipelines/rag.py

volumes:
  mongodb_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  rag-network:
    driver: bridge 